### ISSUE TITLE
Session expired error

### ISSUE THREAD

**Issue by felciano** [jprouty/mint-amazon-tagger#1] opened 2017-10-01 03:44 UTC
Awesome project idea -- thank you for this! I'm testing it out, using your `mint_api` workaround for now, and Chromium seems to be launching correctly and logging in, but I nevertheless am getting a session expiry error:
```
mint_api.MintException: Could not parse category data: "<error><code>1</code><description>Session has expired.</description><name></name><type></type></error>"
```
Any suggestions for debugging?

**Comment by jprouty** [comment] 2017-11-01 20:12
I would recommend trying this w/ python3. For some reason, python2.7 was giving me trouble on all platforms (with somewhat varying errors).

**Comment by felciano** [comment] 2017-11-25 21:08
I've rebuilt my set up with `pipenv` and python3, and am still running into issues when connecting to mint:

```
Traceback (most recent call last):
  File "./tagger.py", line 1226, in <module>
    main()
  File "./tagger.py", line 1189, in main
    get_trans_and_categories_from_mint(mint_client, oldest_trans_date))
  File "./tagger.py", line 1036, in get_trans_and_categories_from_mint
    for (cat_id, cat_dict) in mint_client.get_categories().items()])
  File "/path/to/amazon-mint/mint-amazon-tagger/mint_api.py", line 508, in get_categories
    response + '"')
mint_api.MintException: Could not parse category data: "<error><code>1</code><description>Session has expired.</description><name></name><type></type></error>"
```
Any suggestions?

**Comment by felciano** [comment] 2017-11-27 01:31
@jprouty I was able to get your `mint-amazon-tagger` to work when installing your branch of `mintapi`. However I still get failures when using `mintapi` from the command line -- are you able to get that to work? I wonder whether you are using the internal api differently than the commandline code, which is why `mint-amazon-tagger` is able to login and retrieve data but the commandline code is not...

**Comment by jprouty** [comment] 2017-12-19 21:12
@felciano Please try again! I've migrated over to the selenium requests method and it seems to be working flowingly now 👍

**Comment by felciano** [comment] 2017-12-24 04:41
Hi @jprouty I just did a clean install of `mint-amazon-tagger` using `pipenv` and `python3` and things look much improved. I've only done dry runs thus far but the login seems to be working.

However I am getting a `Do you want the application “Python.app” to accept incoming network connections?` (running OSX 10.12.6) which is odd, since I haven't changed python configurations. Is this possibly a side effect of switching to heavier use of Selenium?

**Comment by jprouty** [comment] 2017-12-29 05:04
Glad to hear!

That should be safe. I am pretty confident [seleniumrequests](https://github.com/cryzed/Selenium-Requests) is the cause:

> Before the actual request is made, a local HTTP server is started that serves a single request made by the webdriver instance to get the "standard" HTTP request headers sent by this webdriver; these are cached (only happens once during its lifetime) and later used in conjunction with the Requests library to make the requests look identical to those that would have been sent by the webdriver. Cookies held by the webdriver instance are added to the request headers and those returned in a response automatically set for the webdriver instance.

I'm going to close this issue for now; please reopen if anything persists!

**Closed by jprouty** 2017-12-29 05:04 UTC
