### ISSUE TITLE
Chrome 91 Error "Element not interactable"  

### ISSUE THREAD

**Issue by Will-Milspec** [jprouty/mint-amazon-tagger#76] opened 2021-06-22 14:16 UTC
Hi,

Mint-amazon-tagger has helped immensely! Until mint-amazon-tagger, amazon transactions have always been a big black hole. Thank you! Thank you! Thank you!

Problem:
Recently, the "login to mint" portion of the selenium script fails with this error:

```
Internal error while creating updates: Message: element not interactable
  (Session info: chrome=91.0.4472.114)
```

It worked a few weeks ago:

Environment:
- ubuntu 20
- python 3.8.5
- mint amazon tagger 1.3.5

I installed mint-amazon-tagger via:
- python venv
- pip 

Thanks in advance!

**Comment by Will-Milspec** [comment] 2021-06-27 00:40
some points:
- reviewing the code, i see the mintapi handles logging in 
- someone filed a similar issue w/ mintapi
https://github.com/mrooney/mintapi/issues/265

**Comment by jprouty** [comment] 2021-06-27 04:58
Hi @Will-Milspec,

I often help mintapi debug/fix login issues as well. Would you mind describing here (or on the referenced MintAPI issue) in more detail the sequence of events? Specifically, what intuit pages are you seeing? Are there multiple accounts to choose from? Are you going through 2FA? And if so, what type?

Thanks,
Jeff

**Comment by Will-Milspec** [comment] 2021-06-28 01:33
hi @jprouty  
the issue appears when mintapi/selenium tries to log in via this screen. The selenium script seems to expect an input field and instead finds a div.

i cut out my email address from the image, but the following html renders it:
```
<div id="ius-option-username-0" class="ius-option-username" data-di-mask="">
                my.email@gmail.com
</div>
```

Here's the screenshot:
![mint_login_screen](https://user-images.githubusercontent.com/86306457/123566971-b22fd200-d786-11eb-924e-f848dcf1bb03.png)

**Comment by Will-Milspec** [comment] 2021-07-06 14:09
interestingly, deleting cookies did not get past the problem. 

I first deleted:
- mint.com and intuit.com cookies
- then all cookies...

I assumed deleting cookies would prevent mint from knowing (and displaying in a <div> element) my email address.

**Comment by Will-Milspec** [comment] 2021-07-07 15:46
fyi, i worked around the problem:

- created a new user on my computer (ubuntu)
- logged on as new user
- installed and ran mint-amazon-tagger  using same parameters as before

Upshot:
- With a "blank slate Chrome instance", accounts.intuit.com  did not create a div with my email address

I would have expected that  clearing cookies --i.e. mint.com and intuit.com --would have given the same results..Evidently you need to clear more than those two domains.

**Comment by jprouty** [comment] 2021-07-07 16:07
Hi @Will-Milspec, If that worked for you, clearing the mintapi chrome profile will likely have the same effect. Try: `rm -rf ~/.mintapi ~/.mintapi2020`. I imagine the original issue will reoccur as before on the second run as that new user or after clearing the .mintapi directory.

Code pointers to .mintapi:
- [mintapi code](https://github.com/mrooney/mintapi/blob/master/mintapi/api.py#L1207)
- [mintamazontagger code](https://github.com/jprouty/mint-amazon-tagger/blob/76001c0705b1e2b498c86413df73f16859053c9b/mintamazontagger/args.py#L80) - this is more likely the source of issues for the mint amazon tool (and was intended to use the same session as the mintapi code (I cannot remember why I split them out).

I'll take a closer look at this when I can get a chance. This wasn't replicating for me last time I tried but I'll try again :)

**Comment by kwylie** [comment] 2021-07-26 00:45
Having this issue as well.  Running the above command doesn't clear up my issue unfortunately.

**Comment by jprouty** [comment] 2021-07-26 06:18
I have a fix in the works. Might be a two step process (need to get mintapi updated first).

**Comment by jprouty** [comment] 2022-01-01 00:05
Hi @kwylie and @Will-Milspec,

Are either of you still having this issue?

Since the original report, I have both fixed MintAPI and moved away from MintAPI entirely (new mintclient that is custom to this tool has been created).

I am going to proactively close this issue; please reopen if something similar is still occurring! Thanks.

**Closed by jprouty** 2022-01-01 00:05 UTC
