### ISSUE TITLE
Pypi issue with PyQt5 dep

### ISSUE THREAD

**Issue by EliW** [jprouty/mint-amazon-tagger#93] opened 2022-01-23 02:33 UTC
Hey there, gonna try to make this as good of a bug report as possible, but I did multiple things and got different failures and wasn't good about documenting each step since "I'm sure it will work after this".    *slaps his own developer wrist*.

But typing up my experience so far.  Happy to help debug, just let me know what bits you want me to try and document better.

### Setup
Running on MacOS 12.1, started off just going 'meh lemme install binary' because I was feeling lazy.

### Amazon Download Issues
So I first decided to tell it that I would do the logging in myself (start off not trusting software, later read the code to make sure it's OK to trust it, right?) ... Otherwise left everything in the GUI at the defaults and went for it.   It got to Amazon, let me log in, and then took over heading to the download page, making the 3 requests, and waiting (giving me a MIGHT TAKE HOURS warning).   It finished in like 3 minutes, and it then downloaded .... only the Items.csv, not the other two.....  And then it basically hung up.  It said it was going to mint in the status window, but never went there.

Eventually I killed it, and manually downloaded the other two files

### Fine, use pre-fetch, use auto-login Mint --- Two accounts issue
Not sure how much this is really an issue.  But I went to run stuff again (oh, immediately I went to do that and started getting --user-data errors because I guess of the aborted attempt.  I killed the software and restarted it, that worked).    But after logging into Mint, it immediately went to 'getting transactions', but I was dropped onto the post-login "Please choose which Mint account you want to use", since you can have multiple accounts associated with a email/pass.   I went ahead and manually selected the right one, and it 'seemed' to work but was a touch odd that it never mentioned in the status "Please select account" or something.    (Also, for the rest of the steps here, the mint/chrome window under control never changed.  I guess that's expected because it's doing API level work at that point, not webscraping?   Anyway

### (not bug but) - Tweaking Categories?
It then got to the point of showing me the amazing looking screen with all the matches it found and how it was going to itemize them for me, etc.   At this point there were a number of them that I wanted to change categories on.  (Honestly in general I'd like to reduce the number of categories it was creating, it was getting really specific).  But the UI didn't seem to let me?  Right-click on a row didn't do anything, and clicking on it would open Amazon for that transaction in another window.   Is there not a way to modify them here before sending?

### Mint Go Boom
So I decided I'd change the categories afterwards on mint, because it was still better than having everything be 'shopping'.  And so I told it to go ahead, it churned for a short bit, and then I get an error (wish I'd screen-capped) but saying something like:  Mint API error: 'close' not supported.   I assumed that this meant it still worked, just that it couldn't properly close down the API connection, whatever.  But when I went into Mint to look, none of the changes appear to have taken place.  Welllll fudge

### OK, Screw it, Command Line
At this point I decided I wanted more control, and dry-runs, and command line options.  So I just decided to pip3 install it.   Well I started getting a ton of errors throughout the install process.  Looks like it was trying to install PyQt5 ... And basically it got an error on the latest version, and so started stepping back over like 10 versions getting the same error each time, and then eventually gave up.   Here's the error:
```
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/2t/f05krxq14jb2zwclnsnbd2gm0000gn/T/tmp6mxfoa1l
       cwd: /private/var/folders/2t/f05krxq14jb2zwclnsnbd2gm0000gn/T/pip-install-i0kwr7h3/pyqt5_c8d15227da524f1a9fdc6f55e254355e
  Complete output (29 lines):
  Traceback (most recent call last):
    File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
      hook = backend.prepare_metadata_for_build_wheel
  AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "/private/var/folders/2t/f05krxq14jb2zwclnsnbd2gm0000gn/T/pip-build-env-l64p52yn/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 51, in build_wheel
      project = AbstractProject.bootstrap('pep517')
    File "/private/var/folders/2t/f05krxq14jb2zwclnsnbd2gm0000gn/T/pip-build-env-l64p52yn/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
      project.setup(pyproject, tool, tool_description)
    File "/private/var/folders/2t/f05krxq14jb2zwclnsnbd2gm0000gn/T/pip-build-env-l64p52yn/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 587, in setup
      self.apply_user_defaults(tool)
    File "project.py", line 63, in apply_user_defaults
      super().apply_user_defaults(tool)
    File "/private/var/folders/2t/f05krxq14jb2zwclnsnbd2gm0000gn/T/pip-build-env-l64p52yn/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
      super().apply_user_defaults(tool)
    File "/private/var/folders/2t/f05krxq14jb2zwclnsnbd2gm0000gn/T/pip-build-env-l64p52yn/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 234, in apply_user_defaults
      self.builder.apply_user_defaults(tool)
    File "/private/var/folders/2t/f05krxq14jb2zwclnsnbd2gm0000gn/T/pip-build-env-l64p52yn/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 67, in apply_user_defaults
      raise PyProjectOptionException('qmake',
  sipbuild.pyproject.PyProjectOptionException
  ----------------------------------------
```

The very final error was different, and the install aborted at that time:
```
ERROR: PyQt5 from https://files.pythonhosted.org/packages/7c/5b/e760ec4f868cb77cee45b4554bf15d3fe6972176e89c4e3faac941213694/PyQt5-5.14.0.tar.gz#sha256=0145a6b7de15756366decb736c349a0cb510d706c83fda5b8cd9e0557bc1da72 (from mint-amazon-tagger) has a pyproject.toml file that does not comply with PEP 518: 'build-system.requires' contains an invalid requirement: 'sip >=5.0.1 <6'
```

**Comment by EliW** [comment] 2022-01-23 23:38
Update:  So, appears something odd happened that I didn't realize.   But I was just going into Mint to do some things manually today.   And I suddenly noticed that the updates actually went through, but only some of them?   So a number of the amazon things now show the updated categories/names.    But I swear they didn't last night, in fact, I even made sure to refresh screens etc.   But today, suddenly they are there.

So I guess it worked, but crashed part-way through with that 'close' error?

**Comment by EliW** [comment] 2022-01-23 23:56
another update.  I have gotten the command line version installed now.  For reference on the m1 macs it appears that pip3 PyQt5 just will not work.    Also the stock homebrew one doesn't.   But:
```
brew install pyqt@5
```

Did the trick ... so now playing with command line to see if I can get any better results

**Comment by EliW** [comment] 2022-01-24 00:54
New couple details:

(1) Running command line, after it logs me into Mint, it locks up still saying 'logging into mint' while it's spinning, even though it's done.    However it throws a selenium error and hangs.

(2) Changing it to userwilllogin let it work however.  After doing that, it did it's magic, but I found something interesting happen.   So I was running this off my account first, and now I'm running it against my wife's in order to get the 'rest of the items'.   During that run, it claimed everything was already tagged, so it did nothing.  I had to change it to the retag setting to get it to do hers.

**Comment by jprouty** [comment] 2022-01-28 04:29
Hi @EliW,

Welcome to the tool and apologies you ran into a pile of issues :)

The close issue you ran into is known and fixed at HEAD, I am cutting new binary releases with the fix now to prevent more bug reports. [See more here](https://github.com/jprouty/mint-amazon-tagger/issues/89). The error happens after all updates would have been sent to Mint already.

For the category question, the tool will attempt to maintain and future apply any custom edits you make after the fact at Mint.com. For this reason, I didn't invest time to add the ability to edit any of the information in the tagger tool but left this functionality to the mint product itself. If you feel it'd materially make your life easier, please split off a separate issue as a feature request and document what you'd like to see.

Sorry you ran into some Pypi issues. This isn't part of my normal release or test flow (I usually develop off of HEAD). I have a good idea for how to fix this.

I am going to repurpose / rename this issue to cover the pypi issues you ran into.

For all the other issues, would you mind creating another issue / FR? It's most helpful when each issue is individually actionable. Thanks for all the great info / reports!

**Comment by jprouty** [comment] 2022-01-28 06:03
FYI, I was able to replicate the mint multiple account issue and filed a [unique issue to track this](https://github.com/jprouty/mint-amazon-tagger/issues/95). This is a regression as they must have changed their dom / layout.

Re: homebrew and M1. I don't have an M1 device, so I cannot help you there. I also don't use homebrew on MacOS. PyPI is really the only way to go to get a reliable environment (especially with venv etc). If you look at this project's requirements/macos.txt you'll see some pointers at trying some specific versions that I found work better than the head version.

**Comment by jprouty** [comment] 2022-01-28 06:04
Closing as I've updated my PyPI script to appropriately test / verify the package works.

**Closed by jprouty** 2022-01-28 06:04 UTC

**Comment by jprouty** [comment] 2022-01-28 06:05
(Also, the fact that the pre-built binary version of the tool worked for you at all means that there is a way to install python3 and use pypi to install the appropriate deps to work on your M1, since this is essentially what is happening under the hood in that binary).

**Comment by EliW** [comment] 2022-01-30 21:28
Thanks for all this.   Also I didn't realize about the 'attempts to remember customizations that you'd made in the past'.   Kinda curious how it's doing that actually.  Unless, I guess, you are downloading all the mint transactions and scanning to match item-to-item?   That would only actually remember 'exact' items tho, right?   Not for example, re-cat all things that would be 'Toy' to 'Discretionary Funds' for example.

Thanks again.   Will file separate bugs for any existing stuff as I continue to use it.

**Comment by jprouty** [comment] 2022-01-30 22:57
Hi @EliW,

Happy to help!

Yes, you're correct; the category "memorization" is based on looking at past examples of the same item being categorized away from what the tool would normally expect. You can find that logic here. 

You could also run from source (nearly the same as what you've done to get it working with PyPI) and modify the [category.py](https://github.com/jprouty/mint-amazon-tagger/blob/master/mintamazontagger/category.py#L10-L15) to your liking. To get setup, it should be something like:
```
git clone https://github.com/jprouty/mint-amazon-tagger.git
# You may need to modify mac.txt as you discovered up thread on this issue.
python3 -m pip install -r requirements/base.txt -r requirements/mac.txt
# Now modify mintamazontagger/category.py and run the tool, either gui or cli
python3 -m mintamazontagger.main # gui
python3 -m mintamazontagger.cli # cli
```

Good luck!
Jeff
